// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyV5_L5wlKoIXXZaU7fRThz9YugJEiOTg',
    appId: '1:807036591355:web:84c33efacbcef1b33d245e',
    messagingSenderId: '807036591355',
    projectId: 'fir-flutter-codelab-82142',
    authDomain: 'fir-flutter-codelab-82142.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-82142.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw4zxJCSXT1UOB2oHow2JnKwlbns38bGI',
    appId: '1:807036591355:android:0f49af9509542cf43d245e',
    messagingSenderId: '807036591355',
    projectId: 'fir-flutter-codelab-82142',
    storageBucket: 'fir-flutter-codelab-82142.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARtbrTvCIXwnnkhk41n25xlySitt0paeg',
    appId: '1:807036591355:ios:1af086af8a3bb2963d245e',
    messagingSenderId: '807036591355',
    projectId: 'fir-flutter-codelab-82142',
    storageBucket: 'fir-flutter-codelab-82142.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARtbrTvCIXwnnkhk41n25xlySitt0paeg',
    appId: '1:807036591355:ios:1af086af8a3bb2963d245e',
    messagingSenderId: '807036591355',
    projectId: 'fir-flutter-codelab-82142',
    storageBucket: 'fir-flutter-codelab-82142.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

}